### ISSUE TITLE
sir i want to reproduce your result need datasets of colorectal disease

### ISSUE THREAD

**Issue by anwari-alt** [SahadevPoudel/Colorectal-disease-classification-via-Localization-Guided-Feature-Representation#1]

**Comment by anwari-alt** [comment]
sir i want to reproduce your reaserch paper result need colorectoral disease datasets

**Comment by anwari-alt** [comment]
some code part missing please upload full code

**Comment by anwari-alt** [comment]
issue gives in AUSTROUSCONVLOUTION2D

**Comment by SahadevPoudel** [comment]
Hi, I am unable to make the dataset public due to privacy concern. Could you show errors you got during loading the model?
